### ISSUE TITLE
[BUG]: Installation error for sample configuration

### ISSUE THREAD

**Issue by hanshal101** [kube-vm-project/eSwitch#2]
### Description
I'm trying to install `eSwitch` on my machine but facing several issues. This is my sample-yaml file:
```yaml
apiVersion: eswitchconfig.kube-vm.io/v1
kind: Eswitch
metadata:
  labels:
    app.kubernetes.io/name: eswitch
    app.kubernetes.io/managed-by: kustomize
  name: eswitch-sample
spec:
  ports:
  - interface: ens33
    pvid: 10
    vlans: [10, 20, 30]
    xdpmode: native
  - interface: vnet0
    pvid: 20
    vlans: [20, 30]
    xdpmode: native
```
While these are my network links.
```powershell
lol@lol:~$ ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether 00:0c:29:69:ce:b6 brd ff:ff:ff:ff:ff:ff
    altname enp2s1
3: virbr0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 52:54:00:77:30:7d brd ff:ff:ff:ff:ff:ff
4: br-cff4dc1b240f: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default
    link/ether 02:42:4e:74:8e:31 brd ff:ff:ff:ff:ff:ff
5: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default
    link/ether 02:42:75:ae:d8:37 brd ff:ff:ff:ff:ff:ff
9: veth95972e2@if8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-cff4dc1b240f state UP mode DEFAULT group default
    link/ether ca:a0:24:3c:4d:21 brd ff:ff:ff:ff:ff:ff link-netnsid 1
10: vnet0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master virbr0 state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether fe:54:00:fc:cf:ee brd ff:ff:ff:ff:ff:ff
```
Here is my running VM
```powershell
lol@lol:~$ virsh list
 Id   Name        State
---------------------------
 1    alpine-vm   running
```
And these are the errors/logs while deploying the configfile
```powershell
2025-03-07T21:05:08Z    ERROR   parsing switch configuration    {"controller": "eswitch", "controllerGroup": "eswitchconfig.kube-vm.io", "controllerKind": "Eswitch", "Eswitch": {"name":"eswitch-sample","namespace":"default"}, "namespace": "default", "name": "eswitch-sample", "reconcileID": "2982dd84-4fe8-43f4-9686-0e4557e03f8f", "error": "route ip+net: no such network interface"}
```
It says no such network interface is present.

### Solution
